package communication.enums;

import communication.packets.Packet;
import communication.packets.ResponsePacket;

/**
 * This enum contains all types of packets as String representation.
 * This String is used on the server-side to identify a {@link Packet} before instantiating the corresponding class.
 * However, for increased code flexibility the types includes those of {@link ResponsePacket}'.
 */
public enum PacketType {
    LOGIN_REQUEST, LOGIN_RESPONSE, PERSONAL_DATA_REQUEST, PERSONAL_DATA_RESPONSE, GET_AGENDA_REQUEST, GET_AGENDA_RESPONSE, ADD_VOTE_REQUEST, ADD_VOTE_RESPONSE,
    GET_ACTIVE_VOTING_REQUEST, GET_ACTIVE_VOTING_RESPONSE, INVALID_TOKEN, FAILURE, ADD_TOPIC_REQUEST, REMOVE_TOPIC_REQUEST,
    RENAME_TOPIC_REQUEST, REORDER_TOPIC_REQUEST, VALID_RESPONSE, REQUEST_OF_CHANGE_REQUEST, REQUEST_OF_SPEECH_REQUEST, GET_ALL_REQUESTS_REQUEST,
    GET_ALL_REQUESTS_RESPONSE, ADD_ATTENDEE_REQUEST, GET_ALL_ATTENDEES_REQUEST, GET_ALL_ATTENDEES_RESPONSE, EDIT_USER_REQUEST,
    REMOVE_ATTENDEE_REQUEST, LOGOUT_ATTENDEE_REQUEST, GENERATE_NEW_ATTENDEE_PASSWORD, GENERATE_NEW_ATTENDEE_TOKEN,
    GENERATE_MISSING_ATTENDEE_PASSWORDS, GET_ATTENDEE_PASSWORD_REQUEST, GET_ALL_ATTENDEE_PASSWORDS, LOGOUT_ALL_ATTENDEES, GET_ATTENDEE_DATA_REQUEST,
    GET_VOTINGS_REQUEST, ADD_VOTING_REQUEST_PACKET, REMOVE_VOTING_REQUEST, SET_ATTENDEE_PRESENT_STATUS_REQUEST,
    GET_ALL_ATTENDEE_PASSWORDS_RESPONSE, GET_ATTENDEE_PASSWORD_RESPONSE, CONFERENCE_DATA_REQUEST, CONFERENCE_DATA_RESPONSE, IS_ADMIN_REQUEST, IS_ADMIN_RESPONSE,
    DOWNLOAD_FILE_RESPONSE, DOWNLOAD_FILE_REQUEST, GET_DOCUMENT_LIST_REQUEST, GET_DOCUMENT_LIST_RESPONSE, UPDATE_FILE_REQUEST, UPDATE_FILE_RESPONSE,
    GET_VOTINGS_RESPONSE, START_VOTING_REQUEST, EDIT_VOTING_REQUEST, ADD_MULTIPLE_ATTENDEES_REQUEST, DELETE_FILE_REQUEST, SET_REQUEST_STATUS_REQUEST,
    GET_EXISTING_GROUPS_REQUEST, GET_EXISTING_GROUPS_RESPONSE, ADD_FULL_AGENDA_REQUEST, DELETE_AGENDA_REQUEST, GET_PREVIOUS_VOTINGS_REQUEST,
    DOWNLOAD_QR_REQUEST, DOWNLOAD_ALL_QR_REQUEST;
}
